[package]
name = "pahserver"
version = "0.0.1"
edition = "2018"
default-run = "pahserver"

[dependencies]
tokio = { version = "1", features = ["full"] }
sodiumoxide = "0.2"
rusqlite = "0.24"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
structopt = "0.3"
